# Generated by Django 5.2.17 on 2026-08-11 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('photo', 'photo'), ('card', 'card'), ('video', 'video'), ('fashion', 'fashion'), ('copyStyle', 'copyStyle'), ('marketplacePackage', 'marketplacePackage')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('processing', 'processing'), ('success', 'success'), ('failed', 'failed')], default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('message', models.CharField(blank=True, default='Vazifa navbatda', max_length=200)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('settings', models.JSONField(default=dict)),
                ('results', models.JSONField(blank=True, default=list)),
                ('tokens_charged', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'idempotency_key'), name='unique_idempotency_key_per_user')],
            },
        ),
    ]
