# Generated by Django 5.2.17 on 2026-08-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
