# Generated by Django 5.2.17 on 2026-08-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_generationjob_cancelled_generationjob_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
