# Generated by Django 5.2.17 on 2026-08-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrun',
            name='report',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
